### ISSUE TITLE
Fenced code blocks issue

### ISSUE THREAD

**Issue by arbrandes** [hastexo/olx-utils#9]
@fghaas reports that yaml fenced coded blocks are not rendered properly.

**Comment by fghaas** [comment]
Detail on this:

Here's some Markdown input:

    ```yaml
      mysubnet:
        type: OS::Neutron::Subnet
        properties:
          cidr: 10.0.0.1/24
          name: mysubnet
          network:
            get_resource: mynetwork
    ```

olx-utils renders this into:

```html
<div class="codehilite"><pre><span></span><code>  <span class="l l-Scalar l-Scalar-Plain">mysubnet</span><span class="p p-Indicator">:</span>
    <span class="l l-Scalar l-Scalar-Plain">type</span><span class="p p-Indicator">:</span> <span class="l l-Scalar l-Scalar-Plain">OS::Neutron::Subnet</span>
    <span class="l l-Scalar l-Scalar-Plain">properties</span><span class="p p-Indicator">:</span>
      <span class="l l-Scalar l-Scalar-Plain">cidr</span><span class="p p-Indicator">:</span> <span class="l l-Scalar l-Scalar-Plain">10.0.0.1/24</span>
      <span class="l l-Scalar l-Scalar-Plain">name</span><span class="p p-Indicator">:</span> <span class="l l-Scalar l-Scalar-Plain">mysubnet</span>
      <span class="l l-Scalar l-Scalar-Plain">network</span><span class="p p-Indicator">:</span>
        <span class="l l-Scalar l-Scalar-Plain">get_resource</span><span class="p p-Indicator">:</span> <span class="l l-Scalar l-Scalar-Plain">mynetwork</span>
</code></pre></div>
```

When displaying this in a browser (c&p'ing the above HTML into a file and opening it in Chromium, it is appropriately rendered in monospace with all whitespace preserved, as you would expect from a `pre` block.

However when displaying this in a vertical in Open edX, the outcome looks as follows:

```
mysubnet:type:OS::Neutron::Subnetproperties:cidr:10.0.0.1/24name:mysubnetnetwork:get_resource:mynetwork
```

I.e. no whitespace preservation whatsoever, everything on one line.
